const moveData = {
  getStartedData: {
    house_type: "1 Bedroom, small(600 - 800 sqf)",
    moving_from: {
      place_name: "Ruiru, Kiambu, Kenya",
      latitude: 36.95694,
      longitude: -1.14889,
    },
    moving_to: {
      place_name: "Texas City, Texas, United States",
      latitude: -94.917549,
      longitude: 29.396013,
    },
  },
  items: [
    {
      item: "Sofa",
      category: "living room",
      count: 3,
    },
    {
      item: "Table",
      category: "living room",
      count: 2,
    },
    {
      item: "Cabinet",
      category: "living room",
      count: 3,
    },
    {
      item: "Sofa",
      category: "living room",
      count: 1,
    },
    {
      item: "Bed",
      category: "bedroom",
      count: 1,
    },
    {
      item: "Cooker",
      category: "kitchen",
      count: 1,
    },
    {
      item: "Boxes",
      category: "others",
      count: 3,
    },
  ],
  quotes: {
    mover: [{}],
  },
};

const rates = [
  {
    id: 1,
    item_name: "cabinet",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 2,
    item_name: "sofa",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 3,
    item_name: "table",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 4,
    item_name: "bed",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 5,
    item_name: "side table",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 6,
    item_name: "dining chair",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 7,
    item_name: "dining table",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 8,
    item_name: "cooker",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 9,
    item_name: "fridge",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 10,
    item_name: "washing machine",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 11,
    item_name: "microwave",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 12,
    item_name: "office chair",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 13,
    item_name: "office table",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 14,
    item_name: "grill",
    count: 0,
    category: "outdoor",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 15,
    item_name: "boxes",
    count: 0,
    category: "boxes",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$R0Vbe2t4Ct9/BzEqXhisfu7bcSelCbdsMTTUJVKqppAcOBZyhWQsm",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 16,
    item_name: "cabinet",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 17,
    item_name: "sofa",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 18,
    item_name: "table",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 19,
    item_name: "bed",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 20,
    item_name: "side table",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 21,
    item_name: "dining chair",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 22,
    item_name: "dining table",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 23,
    item_name: "cooker",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 24,
    item_name: "fridge",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 25,
    item_name: "washing machine",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 26,
    item_name: "microwave",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 27,
    item_name: "office chair",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 28,
    item_name: "office table",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 29,
    item_name: "grill",
    count: 0,
    category: "outdoor",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 30,
    item_name: "boxes",
    count: 0,
    category: "boxes",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 3,
      full_name: "James Sonya",
      phone: "0797165748",
      password_digest:
        "$2a$12$wo919A8zMXcj13eA82URzOG2EVjNltx9uv8BEUhr3TXo15vf6QR4C",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "amessonya@gmail.com",
    },
  },
  {
    id: 31,
    item_name: "cabinet",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 32,
    item_name: "sofa",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 33,
    item_name: "table",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 34,
    item_name: "bed",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 35,
    item_name: "side table",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 36,
    item_name: "dining chair",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 37,
    item_name: "dining table",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 38,
    item_name: "cooker",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 39,
    item_name: "fridge",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 40,
    item_name: "washing machine",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 41,
    item_name: "microwave",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 42,
    item_name: "office chair",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 43,
    item_name: "office table",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 44,
    item_name: "grill",
    count: 0,
    category: "outdoor",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 45,
    item_name: "boxes",
    count: 0,
    category: "boxes",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 4,
      full_name: "Denis Maina",
      phone: "0797165749",
      password_digest:
        "$2a$12$esL43tnvz1EVloxu4oe0qePZI.LI/un3JnY1l8kZqVGKBpg3pPjBy",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "denismaina@gmail.com",
    },
  },
  {
    id: 46,
    item_name: "cabinet",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 47,
    item_name: "sofa",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 48,
    item_name: "table",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 49,
    item_name: "bed",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 50,
    item_name: "side table",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 51,
    item_name: "dining chair",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 52,
    item_name: "dining table",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "10.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 53,
    item_name: "cooker",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "150.0",
    price_per_unit: "10.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 54,
    item_name: "fridge",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 55,
    item_name: "washing machine",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 56,
    item_name: "microwave",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "20.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 57,
    item_name: "office chair",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 58,
    item_name: "office table",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "550.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 59,
    item_name: "grill",
    count: 0,
    category: "outdoor",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "32.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
  {
    id: 60,
    item_name: "boxes",
    count: 0,
    category: "boxes",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 5,
      full_name: "Sir Elijah",
      phone: "0797165711",
      password_digest:
        "$2a$12$9yzUVb7NZal7pUaMbkXW5uDkUR6BC93DT9WwsMiAbfM9vrH8T9oZO",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "sirelijah@gmail.com",
    },
  },
];

const quotes = [];

moveData.items.map((item) =>
  // eslint-disable-next-line array-callback-return
  rates.map((rate) => {
    if (
      item["item"]?.toLocaleLowerCase() ===
      rate["item_name"]?.toLocaleLowerCase() //0(N)2
    ) {
      quotes.push({
        item_name: item.item,
        item_count: item.count,
        ppu: rate.price_per_unit,
        subtotal: item.count * rate.price_per_unit,
        mover_id: rate.user.id,
      });
    }
  })
);

function transformArr(orig) {
  var newArr = [],
    mover_ids = {},
    i,
    j,
    cur;
  for (i = 0, j = orig.length; i < j; i++) {
    cur = orig[i];
    if (!(cur.mover_id in mover_ids)) {
      mover_ids[cur.mover_id] = { mover_id: cur.mover_id, mover_quotes: [] };
      newArr.push(mover_ids[cur.mover_id]);
    }

    mover_ids[cur.mover_id].mover_quotes.push(cur);
  }
  return newArr;
}

const compiledQuotes = transformArr(quotes);

const quotesIncludingGrandTotal = compiledQuotes.map(
  (quote) => {
    quote = { ...quote, total: 0 };

    console.log(
      quote.mover_quotes.map((q) =>
        q.subtotal.reduce((initial, curr) => (initial += curr))
      )
    );
  }
  // (quote.total += quote.subtotal)
);

console.log(quotesIncludingGrandTotal);

const t = [
  [
    {
      mover_id: 2,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 2,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 2,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 2,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 2,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 2,
        },
      ],
      total: 1050,
    },
    {
      mover_id: 2,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 2,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 2,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 2,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 2,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 2,
        },
      ],
      total: 100,
    },
    {
      mover_id: 2,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 2,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 2,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 2,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 2,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 2,
        },
      ],
      total: 1050,
    },
    {
      mover_id: 2,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 2,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 2,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 2,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 2,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 2,
        },
      ],
      total: 350,
    },
    {
      mover_id: 2,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 2,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 2,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 2,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 2,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 2,
        },
      ],
      total: 50,
    },
    {
      mover_id: 2,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 2,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 2,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 2,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 2,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 2,
        },
      ],
      total: 30,
    },
    {
      mover_id: 2,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 2,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 2,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 2,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 2,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 2,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 2,
        },
      ],
      total: 90,
    },
  ],
  [
    {
      mover_id: 3,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 3,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 3,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 3,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 3,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 3,
        },
      ],
      total: 1050,
    },
    {
      mover_id: 3,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 3,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 3,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 3,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 3,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 3,
        },
      ],
      total: 100,
    },
    {
      mover_id: 3,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 3,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 3,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 3,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 3,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 3,
        },
      ],
      total: 1050,
    },
    {
      mover_id: 3,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 3,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 3,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 3,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 3,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 3,
        },
      ],
      total: 350,
    },
    {
      mover_id: 3,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 3,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 3,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 3,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 3,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 3,
        },
      ],
      total: 50,
    },
    {
      mover_id: 3,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 3,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 3,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 3,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 3,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 3,
        },
      ],
      total: 30,
    },
    {
      mover_id: 3,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 3,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 3,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 3,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 3,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 3,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 3,
        },
      ],
      total: 90,
    },
  ],
  [
    {
      mover_id: 4,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 4,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 4,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 4,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 4,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 4,
        },
      ],
      total: 1050,
    },
    {
      mover_id: 4,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 4,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 4,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 4,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 4,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 4,
        },
      ],
      total: 100,
    },
    {
      mover_id: 4,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 4,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 4,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 4,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 4,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 4,
        },
      ],
      total: 1050,
    },
    {
      mover_id: 4,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 4,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 4,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 4,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 4,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 4,
        },
      ],
      total: 350,
    },
    {
      mover_id: 4,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 4,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 4,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 4,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 4,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 4,
        },
      ],
      total: 50,
    },
    {
      mover_id: 4,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 4,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 4,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 4,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 4,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 4,
        },
      ],
      total: 30,
    },
    {
      mover_id: 4,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 4,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 4,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 4,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 4,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 4,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 4,
        },
      ],
      total: 90,
    },
  ],
  [
    {
      mover_id: 5,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 5,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 5,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 5,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 5,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 5,
        },
      ],
      total: 1050,
    },
    {
      mover_id: 5,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 5,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 5,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 5,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 5,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 5,
        },
      ],
      total: 100,
    },
    {
      mover_id: 5,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 5,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 5,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 5,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 5,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 5,
        },
      ],
      total: 1050,
    },
    {
      mover_id: 5,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 5,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 5,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 5,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 5,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 5,
        },
      ],
      total: 350,
    },
    {
      mover_id: 5,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 5,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 5,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 5,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 5,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 5,
        },
      ],
      total: 50,
    },
    {
      mover_id: 5,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 5,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 5,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 5,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 5,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 5,
        },
      ],
      total: 30,
    },
    {
      mover_id: 5,
      mover_quotes: [
        {
          item_name: "Sofa",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Table",
          item_count: 2,
          ppu: "50.0",
          subtotal: 100,
          mover_id: 5,
        },
        {
          item_name: "Cabinet",
          item_count: 3,
          ppu: "350.0",
          subtotal: 1050,
          mover_id: 5,
        },
        {
          item_name: "Sofa",
          item_count: 1,
          ppu: "350.0",
          subtotal: 350,
          mover_id: 5,
        },
        {
          item_name: "Bed",
          item_count: 1,
          ppu: "50.0",
          subtotal: 50,
          mover_id: 5,
        },
        {
          item_name: "Cooker",
          item_count: 1,
          ppu: "30.0",
          subtotal: 30,
          mover_id: 5,
        },
        {
          item_name: "Boxes",
          item_count: 3,
          ppu: "30.0",
          subtotal: 90,
          mover_id: 5,
        },
      ],
      total: 90,
    },
  ],
];
