const moveData = {
  getStartedData: {
    house_type: "1 Bedroom, small(600 - 800 sqf)",
    moving_from: {
      place_name: "Ruiru, Kiambu, Kenya",
      latitude: 36.95694,
      longitude: -1.14889,
    },
    moving_to: {
      place_name: "Texas City, Texas, United States",
      latitude: -94.917549,
      longitude: 29.396013,
    },
  },
  items: [
    {
      item_name: "Sofa",
      category: "living room",
      count: 3,
    },
    {
      item: "Table",
      category: "living room",
      count: 2,
    },
    {
      item: "Cabinet",
      category: "living room",
      count: 3,
    },
    {
      item: "Sofa",
      category: "living room",
      count: 1,
    },
    {
      item: "Bed",
      category: "bedroom",
      count: 1,
    },
    {
      item: "Cooker",
      category: "kitchen",
      count: 1,
    },
    {
      item: "Boxes",
      category: "others",
      count: 3,
    },
  ],
  quotes: {
    mover: [{}],
  },
};

const rates = [
  {
    id: 15,
    item_name: "boxes",
    count: 0,
    category: "boxes",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 5,
    item_name: "side table",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 4,
    item_name: "bed",
    count: 0,
    category: "bedroom",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 10,
    item_name: "washing machine",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 6,
    item_name: "dining chair",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 14,
    item_name: "grill",
    count: 0,
    category: "outdoor",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 13,
    item_name: "office table",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 2,
    item_name: "sofa",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 7,
    item_name: "dining table",
    count: 0,
    category: "dining room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 1,
    item_name: "cabinet",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "350.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 8,
    item_name: "cooker",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 11,
    item_name: "microwave",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 9,
    item_name: "fridge",
    count: 0,
    category: "kitchen",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 3,
    item_name: "table",
    count: 0,
    category: "living room",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "50.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
  {
    id: 12,
    item_name: "office chair",
    count: 0,
    category: "office",
    distance: "10",
    flat_price: "450.0",
    price_per_unit: "30.0",
    discount: "0.5",
    user: {
      id: 2,
      full_name: "Jane Doe",
      phone: "0797165747",
      password_digest:
        "$2a$12$zEJ4KSWlXG7l4Snucnqb7.NSDBkCUAkvxal1DxlnsjuyNAd4tcMVG",
      avatar_url: "",
      account_type: "mover",
      type: "Mover",
      location_id: 2,
      email: "janedoe@gmail.com",
    },
  },
];

let fl = moveData.items.map((item) =>
  rates.map((rate) => {
    if (
      item["item_name"]?.toLocaleLowerCase() ===
      rate["item_name"]?.toLocaleLowerCase()
    ) {
      console.log(item.item_name, item.count, rate.price_per_unit);
    }
  })
);
console.log(fl);
